services:
  shared-database-host:
    image: postgres:16-alpine
    restart: unless-stopped
    expose:
      - 5432
    environment:
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_USER=${DATABASE_HOST_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_HOST_PASSWORD}
      - POSTGRES_PORT=5432
    ports:
      # Expose on different port to prevent conflict with local
      - "6543:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_HOST_USERNAME}"]
      interval: 2s
      timeout: 60s
      retries: 20
      start_period: 2s

  backend:
    depends_on:
      shared-database-host:
        condition: service_healthy
    build: ./services/backend
    working_dir: /backend/app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - PYTHONBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PROJECT_NAME=Project
      - DATABASE_HOST_NAME=shared-database-host
      - DATABASE_HOST_PORT=5432
      - DATABASE_HOST_USERNAME=${DATABASE_HOST_USERNAME}
      - DATABASE_HOST_PASSWORD=${DATABASE_HOST_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    command: litestar --app src.main:app run --host=0.0.0.0 --port=8000 --reload
