name: Run tests

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clean up
      run: docker rm $(docker ps -q -a) && docker volume rm $(docker volume ls -q)

    - name: Launch stack
      run: (export $(cat .env.test | xargs) && docker compose --file docker-compose-test.yml up --build -d)

    - name: Run tests
      run: (export $(cat .env.test | xargs) && docker compose exec backend pytest -vv)
